### PR TITLE
Add new-programmer-friendly wrappers for state-space control

### LINKED ISSUE #56: Replace StateSpacev1 with newer WPILib statespace utilities
This is waiting on some work to be done upstream because I really don't want to make our team have to worry about JNI code in our library.

This is mostly a thread to track the progress of @mcm001 and @calcmogul's work upstream

### PR DESCRIPTION
**Pull request by ewpratten**
This PR is rather large and very technical.

## Quick explanation

I have spent the past year teaching myself [state-space](https://en.wikipedia.org/wiki/State-space_representation) control, and experimenting with it in personal projects. A very early implementation of this PR is still sitting in `InfiniteSuspension`. This PR is basically re-adding all of my old statespace utils, but this time: **In Java** (thanks to some work by the WPILib team, because I don't want to put JNI code in this repository)

## The old implementation

In the old implementation, if you wanted to design a state-space controller for a system, you would make a call to one of my generator functions in a Python script. Gradle would then execute this script, and generate the appropriate Java and Protobuf code from it. This generated code was then passed through `protoc`, then imported into the main Java library.

This system was very complicated, and would randomly fail on windows (plus it seems that everyone on this team hates protobuf for no particular reason)

## What has actually been added in this PR

The main goal of this code is to write a middle-layer between us and WPILib. This middle layer is designed to use Grade-9-friendly variable names (not the actual mathematical names), and is documented in such a way that you shouldn't need to understand the math that is happening behind the scenes.

The following wrappers are added:
 - A flywheel controller
 - A single-jointed-arm controller
 - An encoder-based elevator controller
 - A rangefinder-based elevator controller

I have also completely rewritten the dependency system (all the libraries are defined in one file!) to support switching between regular WPILib releases, and using releases built directly from GIT for testing.

There are some other small API changes that were caused by the fact this library is now technically a 2021 project instead of a 2020 project.

## New dependencies

Lib5K now relies on [`ejml`](http://ejml.org/wiki/index.php?title=Main_Page) much more, and has added [`drake`](https://drake.mit.edu/) as a new dependency

### CODE REVIEW

**Comment by ewpratten** [comment]
Alright. I got the green checkmark. This is ready for review

**Review by wm-c — APPROVED** [review]
This looks really good.

What advantages does this provide compared to PID controllers?

**Comment by ewpratten** [comment]
A big one is that the controller gains come from actual math (check out [`FlywheelMath`](https://github.com/frc5024/lib5k/blob/statespace_wrappers/control_loops/src/main/java/io/github/frc5024/lib5k/control_loops/statespace/util/easylqr/FlywheelMath.java) for a little bit of it. The [drake](https://drake.mit.edu/) library does most of the heavy lifting though). Whereas PID gains are basically educated guesses (as I'm sure you remember)

Also things like Linear Quadratic Regulators can take in to account future predictions, and produce output based on that, instead of how PID just basically waits for something to go wrong, then corrects for it.

Finally, all of these classes are using Kalman Filters. This allows us to fuse together multiple medium-accuracy sensor readings into a single high-quality reading)

**Comment by ewpratten** [comment]
If you have the time, I recommend reading some of [Tyler's paper](https://file.tavsys.net/control/controls-engineering-in-frc.pdf). He does a pretty good job of explaining and comparing control methods

**Pull request merged**
