### PR TITLE
Rewrite entire logging system

### PR DESCRIPTION
**Pull request by ewpratten**
## Goals
The goals of this pr are:
 - Clean up RobotLogger
 - Provide a more verbose logging system to help with debugging
 - Provide a cross-platform Python script that can parse and sort logs in realtime

## The new logging format
I have rewritten RobotLogger's output to use this printf format:
```
%s at %.2fs: %s::%s() -> %s
```

This will produce logs that can look like (taken from an example project):
```log
INFO at 0.0000s: io.github.frc5024.libkontrol.statemachines.StateMachine::log() -> Added state: kIdle
INFO at 0.0000s: io.github.frc5024.libkontrol.statemachines.StateMachine::log() -> Set state kIdle as default
INFO at 0.0000s: io.github.frc5024.libkontrol.statemachines.StateMachine::log() -> Added state: kSpinup
INFO at 0.0000s: io.github.frc5024.libkontrol.statemachines.StateMachine::log() -> Added state: kAtGoal
INFO at 0.0000s: io.github.frc5024.lib5k.examples.neo_flywheel.Main::disabledInit() -> Robot disabled
INFO at 0.0000s: io.github.frc5024.lib5k.examples.neo_flywheel.subsystems.Flywheel::handleIdle() -> Became idle
INFO at 105.0000s: io.github.frc5024.lib5k.examples.neo_flywheel.Main::teleopInit() -> Teleop started
INFO at 105.0000s: io.github.frc5024.lib5k.examples.neo_flywheel.subsystems.Flywheel::setGoalVelocity() -> Setting goal velocity to 3000.00
INFO at 105.0000s: io.github.frc5024.lib5k.examples.neo_flywheel.subsystems.Flywheel::handleSpinup() -> Spinning up
INFO at 116.0000s: io.github.frc5024.lib5k.examples.neo_flywheel.Main::disabledInit() -> Robot disabled
INFO at 116.0000s: io.github.frc5024.lib5k.examples.neo_flywheel.subsystems.Flywheel::handleIdle() -> Became idle
```

I am using this regex pattern to [parse the logs](#log-parsing):
```python
r"(.*) at (.*)s: (.*)::(.*)\(\) -> (.*)"
```

## Log parsing

I have introduced a new python script (at `scripts/logreader.py`) for parsing logs. It is based on [971's log parser](http://frc971.org/files/2015-ControlsDocumentation-971.pdf#page=4), and has the following configuration flags:
```
usage: logreader [-h] [-f] [-i IP] [-l] [-t LEVEL_TYPES] [-c CLASSES]
                 [-m METHODS] [-v]
                 team

A tool for reading and sorting log data in real time over a network

positional arguments:
  team                  FRC Team number of the robot or simulation

optional arguments:
  -h, --help            show this help message and exit
  -f, --follow          Setting this flag will follow the logs instead of just
                        dumping a snapshot
  -i IP, --ip IP        Robot or simulation IP address
  -l, --local-simulation
                        Use this flag if connecting to a simulation running on
                        the same computer
  -t LEVEL_TYPES, --level-types LEVEL_TYPES
                        Comma-seperated list of allowed log levels. Options:
                        DEBUG, INFO, WARNING
  -c CLASSES, --classes CLASSES
                        Comma-seperated list of class names. This can be used
                        to only view logs from a specific list of classes
  -m METHODS, --methods METHODS
                        Comma-seperated list of method names. This can be used
                        to only view logs from a specific list of methods
  -v, --verbose         For logreader debugging
```

For example, If I want to connect to a simulation on my laptop, and only view warnings and debug messages from the robot class in real time, I can use this command:
```sh
python3 logreader.py 5024 -l -c Robot -t WARNING,DEBUG
```

If I want everything, I can use:
```sh
python3 logreader.py 5024 -l
```

### How it works

If in simulation mode, the script will look for a file that is generated by the robotlogger at `./FRC_UserProgram.log`. If on a real robot, it will SSH into the bot using the `lvuser` user, and read the `/home/lvuser/FRC_UserProgram.log` file.

This file is read line-by-line through a filter function, then everything that matches the command is printed.

### CODE REVIEW

**Comment by ewpratten** [comment]
This has been tested on real hardware, and in simulation

**Comment by ewpratten** [comment]
Here is a log I just pulled from running testbench on MiniBot:
```
INFO at 1.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::<init>() -> Reporting on FPGA version: 33558530.33558530
INFO at 1.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::<init>() -> Starting reporter thread
INFO at 1.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::handleRailStatuses() -> 3v3 Rail Enabled
INFO at 1.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::handleRailStatuses() -> 5v Rail Enabled
INFO at 1.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::handleRailStatuses() -> 3v3 Rail Enabled
INFO at 2.0000s: io.github.frc5024.testbench.Main::disabled() -> Disabled
INFO at 22.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::update() -> Robot FPGA outputs have been enabled
INFO at 30.0000s: io.github.frc5024.testbench.Main::disabled() -> Disabled
INFO at 30.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::update() -> Robot FPGA outputs have been disabled
INFO at 48.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::update() -> Robot FPGA outputs have been enabled
INFO at 53.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::update() -> Robot FPGA outputs have been disabled
INFO at 53.0000s: io.github.frc5024.testbench.Main::disabled() -> Disabled
INFO at 79.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::update() -> Robot FPGA outputs have been enabled
INFO at 96.0000s: io.github.frc5024.testbench.Main::disabled() -> Disabled
INFO at 97.0000s: io.github.frc5024.lib5k.hardware.ni.roborio.FaultReporter::update() -> Robot FPGA outputs have been disabled
```

**Review by wm-c — CHANGES_REQUESTED** [review]
This looks good to me. The new tools seem useful. The example code needs to be updated to use the newer version of the logger. I also feel that providing the entire class name bloats the log, it should probably just display the actual class name and not the package it is in.

**Comment by ewpratten** [comment]
Having the package name is useful for when you have two classes with the same name. Maybe we do something like chopping out the middle of the package name? Here is an example:
```
INFO at 0.0000s: io...statemachines.StateMachine::log() -> Added state: kIdle
INFO at 0.0000s: io...statemachines.StateMachine::log() -> Set state kIdle as default
INFO at 0.0000s: io...statemachines.StateMachine::log() -> Added state: kSpinup
INFO at 0.0000s: io...statemachines.StateMachine::log() -> Added state: kAtGoal
INFO at 0.0000s: io...neo_flywheel.Main::disabledInit() -> Robot disabled
INFO at 0.0000s: io...subsystems.Flywheel::handleIdle() -> Became idle
INFO at 105.0000s: io...neo_flywheel.Main::teleopInit() -> Teleop started
INFO at 105.0000s: io...subsystems.Flywheel::setGoalVelocity() -> Setting goal velocity to 3000.00
INFO at 105.0000s: io...subsystems.Flywheel::handleSpinup() -> Spinning up
INFO at 116.0000s: io...neo_flywheel.Main::disabledInit() -> Robot disabled
INFO at 116.0000s: io...subsystems.Flywheel::handleIdle() -> Became idle
```

**Review by wm-c — APPROVED** [review]

**Comment by awpratten** [comment]
Looks good. 

The command/subsystem paradigm allows for a simulated parallel processing where you might have concurrent activities each initiated through separate events but interleaved in the logs.  In other logging systems there is a transaction id that is included in the log so that you can see the flow and pull out only those events for the activity you care about.   A contrived example To make my point would be intaking while manipulating the control panel.   The transaction id could be generated from the initial action of the human operator.  Something to consider adding if you feel it would help debugging.

**Comment by ewpratten** [comment]
What generates that ID?

**Comment by awpratten** [comment]
The thing that knows what a transaction looks like ....  which I know is a vague wishy washy answer. I’d think that it would be where the action is initiated.  So if the operator initiates a climb then a transaction id would be acquired and used for all subsequent logging calls that follow directly from that action.  Since the transaction id would need to be unique something in the logger should assign them.  Or you could use utime() at the time of initiation or a random number although that won’t be sequential so maybe not as useful

**Comment by ewpratten** [comment]
that sounds like it could be a hash of the root of the call stack?

**Comment by ewpratten** [comment]
Also, would you like to create a GitHub issue for this, so we can keep track of it and implement it?

**Pull request merged**
